# Application Settings
app:
  name: "Secure File Guard"
  version: "1.0.0"

# Security Settings
security:
  password:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special: true
    special_chars: "!@#$%^&*(),.?\":{}|<>"
  encryption:
    algorithm: "AES-256"
    key_iterations: 100000

# Storage Settings
storage:
  secure_folder: ".secure-file-guard"
  container_name: "container.encrypted"
  metadata_name: "metadata.json"
  max_file_size: 1073741824  # 1GB in bytes
  allowed_extensions: ["*"]  # "*" means all extensions
  compression: true

# Logging Settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "secure_file_guard.log" 