app:
  name: Secure File Guard
  version: 1.0.0
logging:
  file: secure_file_guard.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
security:
  encryption:
    algorithm: AES-256
    key_iterations: 100000
  password:
    min_length: 12
    require_lowercase: true
    require_numbers: true
    require_special: true
    require_uppercase: true
    special_chars: '!@#$%^&*(),.?":{}|<>'
storage:
  allowed_extensions:
  - '*'
  compression: true
  container_name: container.encrypted
  max_file_size: 1073741824
  metadata_name: metadata.json
  secure_folder: .secure-file-guard
